"""Generated by worlds render_embodiment_previews.py; do not hand edit."""

from typing import Final

from ..assets import AssetFormat, AssetProvenance, AssetRole, PackagedAsset, packaged_asset
from ..identity import EmbodimentId

PREVIEWS: Final[dict[EmbodimentId, PackagedAsset]] = {
    EmbodimentId(
        "692780b7966740e5be9ece4df05d42ff43ed24b97c3c02cdcc3c73f46a4da90e"
    ): packaged_asset(
        relpath="official/previews/692780b7966740e5be9ece4df05d42ff43ed24b97c3c02cdcc3c73f46a4da90e.webp",
        sha256="489a653119a2678c165418cb8788e9e315856400096ed6ba0955e5ae64a54aa3",
        size_bytes=3258,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/agilexrobotics/piper_ros",
            revision="ac41fcbcdda598f01b51cf6175ed9a24d0dacadc",
            path="src/piper_description/urdf/piper_description.urdf",
            license_id="MIT",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "4dcc405481ce134790466973c3e15f0e18e50a551864826d25f805a5a98bcbaa"
    ): packaged_asset(
        relpath="official/previews/4dcc405481ce134790466973c3e15f0e18e50a551864826d25f805a5a98bcbaa.webp",
        sha256="523c32e7d9be425797dc44cee2b9e5b6472d622bcf2ddc1c4d3126fe05195fde",
        size_bytes=2360,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/Interbotix/interbotix_ros_manipulators",
            revision="0bb2b0e6d0e619bff02cf74dbd5af5681dcf80c9",
            path="interbotix_ros_xsarms/interbotix_xsarm_descriptions/urdf/vx300s.urdf.xacro",
            license_id="BSD-3-Clause",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "08427bc6d6ee456d6276684a2ee6a27dd0076dd25a315ce6475a3a522ad7435a"
    ): packaged_asset(
        relpath="official/previews/08427bc6d6ee456d6276684a2ee6a27dd0076dd25a315ce6475a3a522ad7435a.webp",
        sha256="41b7b08c52bc3833e38a796ece9a1d7398d29a32f9b4344bea4ea0665cbb1330",
        size_bytes=2486,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/RainbowRobotics/rby1-sdk",
            revision="38df3267e617d22644f6686e8a7e3c4eac3ce2ee",
            path="models/rby1m/urdf/model_v1.3.urdf",
            license_id="Apache-2.0",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "fd1fa5fc145fc6253ca21473354e2c6e17f1006ad95b223daa4c2ae2662fbe64"
    ): packaged_asset(
        relpath="official/previews/fd1fa5fc145fc6253ca21473354e2c6e17f1006ad95b223daa4c2ae2662fbe64.webp",
        sha256="927c3caad9cf720df69952366c098e30fa26b65f56a6b0101fb9986a5b77d368",
        size_bytes=3240,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/unitreerobotics/unitree_ros",
            revision="d96d8f63ae17a7108d4f7229c00ef875ba7129c9",
            path="robots/g1_description/g1_29dof_rev_1_0.urdf",
            license_id="BSD-3-Clause",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "8beb4619bd17e533d931b27f6a943469eca32c2b98f61778e38949da889dc721"
    ): packaged_asset(
        relpath="official/previews/8beb4619bd17e533d931b27f6a943469eca32c2b98f61778e38949da889dc721.webp",
        sha256="7377a2a907d92ea5be9dc7326e8c2b804dcbcc91f02cee450c2be034bed6f135",
        size_bytes=1784,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/UniversalRobots/Universal_Robots_ROS2_Description",
            revision="8c2adeb88e58efa6d5ae376631bd61be7ec49027",
            path="urdf/ur.urdf.xacro",
            license_id="BSD-3-Clause",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "71dc58c47fd43792f477ddd25c8539b6ef5efffd38cf2f522292ccf58ae651c3"
    ): packaged_asset(
        relpath="official/previews/71dc58c47fd43792f477ddd25c8539b6ef5efffd38cf2f522292ccf58ae651c3.webp",
        sha256="99941baeda5fe12a3242dbf08d2e1ccf3b68e1ce642d6fe743c3fb360e337d15",
        size_bytes=1816,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/UniversalRobots/Universal_Robots_ROS2_Description",
            revision="8c2adeb88e58efa6d5ae376631bd61be7ec49027",
            path="urdf/ur.urdf.xacro",
            license_id="BSD-3-Clause",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "da0b43432200044a506dc84e72a911a19fa5bf8d0bb6d3d00dc1ba3865435244"
    ): packaged_asset(
        relpath="official/previews/da0b43432200044a506dc84e72a911a19fa5bf8d0bb6d3d00dc1ba3865435244.webp",
        sha256="344ec4b77c00df69646b3f079f4f8a08db3d5dd44e40f621433554608e6914ee",
        size_bytes=3538,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/YOR-robot/YOR",
            revision="2cc6dd2edcc7aa6d7f3d58e08bce7d2075d80cb6",
            path="robot/yor-description/robot.mjcf",
            license_id="MIT",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "c74c32cd6f3ede9c3fbf99e9123ecde144067f113c7f804b72895162aac6137f"
    ): packaged_asset(
        relpath="humanoid_pkg/previews/c74c32cd6f3ede9c3fbf99e9123ecde144067f113c7f804b72895162aac6137f.webp",
        sha256="83611778a1e1f078653610cd9bd1fff44fbffc015ed7c43228a64769fb37425e",
        size_bytes=4548,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/Sentient-X/humanoid_pkg",
            revision="666bc6b5e00c76b8388a70fcc40a6987e0f1da7a",
            path="urdf/urdf_robot_acc.urdf",
            license_id="BSD-3-Clause",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "4d9128b01622fb2cb34aa22db9813d89c3c5789d20ed96a0bd3269fd82169330"
    ): packaged_asset(
        relpath="official/previews/4d9128b01622fb2cb34aa22db9813d89c3c5789d20ed96a0bd3269fd82169330.webp",
        sha256="8b5655ab2d4f256ce9c994d684778ac8aa9c0343497b8f50e1b7c50a18c0f9c6",
        size_bytes=2096,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/frankarobotics/franka_ros",
            revision="ddd2fffd9de44b02ad15b4bbb2bfa2cec4d60d98",
            path="franka_description/robots/panda/panda.urdf.xacro",
            license_id="Apache-2.0",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "998a6f7a6093c052689fa533c418b1cc90480f4c091d97c18d54512a5af92c9a"
    ): packaged_asset(
        relpath="official/previews/998a6f7a6093c052689fa533c418b1cc90480f4c091d97c18d54512a5af92c9a.webp",
        sha256="8b5655ab2d4f256ce9c994d684778ac8aa9c0343497b8f50e1b7c50a18c0f9c6",
        size_bytes=2096,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/frankarobotics/franka_ros",
            revision="ddd2fffd9de44b02ad15b4bbb2bfa2cec4d60d98",
            path="franka_description/robots/panda/panda.urdf.xacro",
            license_id="Apache-2.0",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "e5523f6fe586138742b107ea674b7d4c63fdcb27ce1c210a4e58becb3dcfa1c8"
    ): packaged_asset(
        relpath="so101/previews/e5523f6fe586138742b107ea674b7d4c63fdcb27ce1c210a4e58becb3dcfa1c8.webp",
        sha256="680d5de1a392b8e0256272b7ddc99931138cbf90024a952155ebed952fc0c7f4",
        size_bytes=2950,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/AbdulazizAlmuzairee/Squint",
            revision="d8ca2fbfb4cef6b6097c71f9ec172c76125a572f",
            path="envs/robot/so101.urdf",
            license_id="MIT",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "0bb3d38347369d5df72d28f0646528e07cfc3accf1da274b931cbbbb1d0e40d9"
    ): packaged_asset(
        relpath="so101/previews/0bb3d38347369d5df72d28f0646528e07cfc3accf1da274b931cbbbb1d0e40d9.webp",
        sha256="d42de80ec8f502d68995187318fac548529c03d27f3bde59d2ca94288103cc14",
        size_bytes=3420,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/AbdulazizAlmuzairee/Squint",
            revision="d8ca2fbfb4cef6b6097c71f9ec172c76125a572f",
            path="envs/robot/so101.urdf",
            license_id="MIT",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "23bc2833bda1f1b9eb5ad9a90774b8b9ac4ca87a416ee093bfbbfd4d37f99192"
    ): packaged_asset(
        relpath="b601_dm/previews/23bc2833bda1f1b9eb5ad9a90774b8b9ac4ca87a416ee093bfbbfd4d37f99192.webp",
        sha256="3b842894e5094a3f48aa1e249ebb25aaa63278057768a44d886ccba494e6464a",
        size_bytes=2560,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/Seeed-Projects/reBotArmController_ROS2",
            revision="a61efe4fa223ca50cd721ef8ebe4a60e90f28bfd",
            path="src/rebotarm_bringup/description/urdf/reBot_B601_DM_with_gripper.urdf",
            license_id="Apache-2.0",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "2061b21100bd859624b2cee57515da0fa56a6baf8330700e7579bc64f15269eb"
    ): packaged_asset(
        relpath="b601_dm/previews/2061b21100bd859624b2cee57515da0fa56a6baf8330700e7579bc64f15269eb.webp",
        sha256="abbfea2ce1c6da7b9e9b10c4f71e160bd91bb78d2eb0733f8c416916fad5265b",
        size_bytes=2382,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/Seeed-Projects/reBotArmController_ROS2",
            revision="a61efe4fa223ca50cd721ef8ebe4a60e90f28bfd",
            path="src/rebotarm_bringup/description/urdf/reBot_B601_DM_with_gripper.urdf",
            license_id="Apache-2.0",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "c1dbe2366ebcc43406d6ff32452e66b3d00ac09c063fd0350577da65ad205a15"
    ): packaged_asset(
        relpath="official/previews/c1dbe2366ebcc43406d6ff32452e66b3d00ac09c063fd0350577da65ad205a15.webp",
        sha256="4ab0bf08431f918e088fc891bcc335935fb8ea5d571f701d54e4400d139d0451",
        size_bytes=2888,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/agilexrobotics/piper_ros",
            revision="ac41fcbcdda598f01b51cf6175ed9a24d0dacadc",
            path="src/piper_description/urdf/piper_description.urdf",
            license_id="MIT",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "247556411179d16439bb955736542729ecf4e52e78dd8e91b0eea29468a771fb"
    ): packaged_asset(
        relpath="b601_dm/previews/247556411179d16439bb955736542729ecf4e52e78dd8e91b0eea29468a771fb.webp",
        sha256="abbfea2ce1c6da7b9e9b10c4f71e160bd91bb78d2eb0733f8c416916fad5265b",
        size_bytes=2382,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/Seeed-Projects/reBotArmController_ROS2",
            revision="a61efe4fa223ca50cd721ef8ebe4a60e90f28bfd",
            path="src/rebotarm_bringup/description/urdf/reBot_B601_DM_with_gripper.urdf",
            license_id="Apache-2.0",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
    EmbodimentId(
        "282e7aac9e8f1515f391c7b5e249e556848a44ee7907d086d45672725f63ee5b"
    ): packaged_asset(
        relpath="ai_worker/previews/282e7aac9e8f1515f391c7b5e249e556848a44ee7907d086d45672725f63ee5b.webp",
        sha256="9070b294059cb1fae6491783a99af1f62468da6c8e538b58567236cf0e70ddc4",
        size_bytes=2550,
        format=AssetFormat.OTHER,
        role=AssetRole.OTHER,
        media_type="image/webp",
        provenance=AssetProvenance(
            repository="https://github.com/ROBOTIS-GIT/ai_worker",
            revision="e02c883f57fed84e06d0be6728334036cb362acf",
            path="ffw_description/urdf/ffw_bg2_rev4_follower/ffw_bg2_follower.urdf",
            license_id="Apache-2.0",
            generator="worlds/render_embodiment_previews/v1; arm practice initial posture",
        ),
    ),
}
