#!/usr/bin/env python3
"""Expand the vendored yubi-sw hand xacro into the canonical plain URDF.

The source of truth is the pinned upstream macro file
``assets/yubi_description/urdf/yubi_hand.urdf.xacro`` (airoa-org/yubi-sw);
this tool renders the plain ``yubi_hands.urdf`` the registry pins. Requires
the ``xacro`` package (tool-only dependency, like mujoco for mjcf_to_urdf):

    uv run --with xacro python tools/expand_yubi_xacro.py
"""

from __future__ import annotations

from pathlib import Path

import xacro

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/yubi_description/urdf/yubi_hand.urdf.xacro"
TARGET = ROOT / "assets/yubi_description/urdf/yubi_hands.urdf"


def render() -> bytes:
    document = xacro.process_file(str(SOURCE))
    # Serialize only the <robot> element with our own stable banner — xacro's
    # default banner embeds the absolute build path, which is not deterministic.
    body = document.documentElement.toprettyxml(indent="  ")
    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/expand_yubi_xacro.py from "
        "assets/yubi_description/urdf/yubi_hand.urdf.xacro -->\n"
    )
    return (header + body).encode()


def main() -> None:
    TARGET.write_bytes(render())


if __name__ == "__main__":
    main()
