#!/usr/bin/env python3
"""Expand the vendored yubi-sw hand xacro into the canonical plain URDF.

The source of truth is the pinned upstream macro file
``assets/yubi_description/urdf/yubi_hand.urdf.xacro`` (airoa-org/yubi-sw);
this tool renders the plain ``yubi_hands.urdf`` the registry pins, then
grafts the Quest head links (the das-umi composite pattern): the head is an
independently tracked body under a floating joint, and the head→optical
joint carries an identity origin because the measured extrinsic rides the
capture data (``/sxd/extrinsics``), never the description. Requires the
``xacro`` package (tool-only dependency, like mujoco for mjcf_to_urdf):

    uv run --with xacro python tools/expand_yubi_xacro.py
"""

from __future__ import annotations

from pathlib import Path

import xacro

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/yubi_description/urdf/yubi_hand.urdf.xacro"
TARGET = ROOT / "assets/yubi_description/urdf/yubi_hands.urdf"

# The Quest head composite (das-umi naming): the registry mounts the ``base``
# head camera on ``quest3s_head``.
_QUEST_HEAD_SUFFIX = """  <link name="quest3s_head"/>
  <joint name="quest_origin_to_head" type="floating">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="quest_origin"/>
    <child link="quest3s_head"/>
  </joint>
  <link name="quest3s_camera_optical"/>
  <joint name="quest3s_head_to_camera_optical" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="quest3s_head"/>
    <child link="quest3s_camera_optical"/>
  </joint>
</robot>"""


def render() -> bytes:
    document = xacro.process_file(str(SOURCE))
    # Serialize only the <robot> element with our own stable banner — xacro's
    # default banner embeds the absolute build path, which is not deterministic.
    body = document.documentElement.toprettyxml(indent="  ")
    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/expand_yubi_xacro.py from "
        "assets/yubi_description/urdf/yubi_hand.urdf.xacro -->\n"
    )
    if "</robot>" not in body:
        raise ValueError("rendered xacro has no closing <robot> element")
    body = body.replace("</robot>", _QUEST_HEAD_SUFFIX)
    return (header + body).encode()


def main() -> None:
    TARGET.write_bytes(render())


if __name__ == "__main__":
    main()
