#!/usr/bin/env python3
"""Expand the vendored yubi-sw hand xacro into the canonical plain URDF.

The source of truth is the pinned upstream macro file
``assets/yubi_description/urdf/yubi_hand.urdf.xacro`` (airoa-org/yubi-sw);
this tool renders the plain ``yubi_hands.urdf`` the registry pins. Quest
controllers are tracking inputs in upstream YUBI; a Quest headset and
passthrough camera pair are deliberately not grafted onto that hardware.
Requires the ``xacro`` package (tool-only dependency, like mujoco for
mjcf_to_urdf):

    uv run --with xacro python tools/expand_yubi_xacro.py
"""

from __future__ import annotations

from pathlib import Path

import xacro

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/yubi_description/urdf/yubi_hand.urdf.xacro"
TARGET = ROOT / "assets/yubi_description/urdf/yubi_hands.urdf"

def render() -> bytes:
    document = xacro.process_file(str(SOURCE))
    for name, xyz in (
        ("quest_origin_to_left", "0 0.16 0"),
        ("quest_origin_to_right", "0 -0.16 0"),
    ):
        joints = [
            joint
            for joint in document.getElementsByTagName("joint")
            if joint.getAttribute("name") == name
        ]
        if len(joints) != 1:
            raise ValueError(f"rendered xacro needs one {name!r} joint")
        origins = joints[0].getElementsByTagName("origin")
        if len(origins) != 1:
            raise ValueError(f"rendered xacro joint {name!r} needs one origin")
        origins[0].setAttribute("xyz", xyz)
    # Serialize only the <robot> element with our own stable banner — xacro's
    # default banner embeds the absolute build path, which is not deterministic.
    body = document.documentElement.toprettyxml(indent="  ")
    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/expand_yubi_xacro.py from "
        "assets/yubi_description/urdf/yubi_hand.urdf.xacro -->\n"
    )
    if "</robot>" not in body:
        raise ValueError("rendered xacro has no closing <robot> element")
    return (header + body).encode()


def main() -> None:
    TARGET.write_bytes(render())


if __name__ == "__main__":
    main()
